### PR TITLE
Add OSGi enRoute templates for bndtools 3.4

### PR DESCRIPTION
**Pull request by njbartlett**
Template source in bndtools/bndtools/osgi.enroute.bndtools.templates

Signed-off-by: Neil Bartlett <njbartlett@gmail.com>

### CODE REVIEW

**Review by bjhargrave — CHANGES_REQUESTED** [review]
This PR can't be used as is. There should not be binaries in the repo. Also I thought you didn't want the source code for the templates in bndtools repo? We need to have the source code some where for future changes, then we need to put the built jar in a maven repo which this workspace can refer to it.

**Comment by njbartlett** [comment]
@bjhargrave As stated in my comment above, the source for the template is in bndtools master. Where do you suggest we put the JAR? We can't have the source code in this repo because then everybody would get a copy of it when they initialise a new enRoute workspace.

**Comment by bjhargrave** [comment]
If we do not want the enroute template source code in the bndtools repo, I would suggest a new git repo under the osgi organization such as osgi.enroute.bndtools or osgi.enroute.bndtools.templates. The jar can be published to https://oss.sonatype.org/content/groups/osgi (see  https://github.com/osgi/workspace/blob/master/cnf/ext/enroute.bnd#L24)

**Comment by njbartlett** [comment]
I only said that the source cannot be in *this* repo (osgi/workspace). I don't mind if it's in Bndtools. The only thing is that it would create an ordering issue... we want a release of this JAR to go into a Maven repo and that would naturally happen when Bndtools 3.4 is released, but you've indicated that 3.4 should not be released without the enRoute templates.

**Comment by njbartlett** [comment]
Sorry hit enter too early... if you prefer the source for this template to go into a new repo owned by OSGi, then can you create such a repo? Then I will raise a PR against that.

**Comment by bjhargrave** [comment]
> I only said that the source cannot be in this repo (osgi/workspace). I don't mind if it's in Bndtools.

Sorry, I was confused by Richard and Mike who were saying today that the dependency on the enroute templates in the bndtools repo was a blocking issue for them/you.

I agree it would be fine to leave the source in the bndtools repo/build.

**Comment by njbartlett** [comment]
On the other hand... if the source for the enRoute template is in Bndtools then changes to that template are dependent on the Bndtools release lifecycle, and are outside full control of the Alliance. I'm thinking it's better for the source to be in an OSGi-owned repo.

**Comment by bjhargrave** [comment]
> I'm thinking it's better for the source to be in an OSGi-owned repo.

This then would mean that bndtools template model is API and cannot be changed in non-backwards compatible ways.

**Comment by njbartlett** [comment]
It's my intention for it to be API, and it's been possible for users to build their own templates since 3.2.

**Comment by bjhargrave** [comment]
There is a https://github.com/osgi/osgi.enroute.template project which seems to hold some source for the bndtools template for OSGi enRoute. I am guessing this is the right repo to use for the bndtools template source. Perhaps you can work in a branch here until we are happy and can then merge to master.

**Comment by njbartlett** [comment]
Okay I'll raise the PR there for the source. Closing this PR, will open a new one when the template binary is pulled in as a maven dependency.

**Comment by njbartlett** [comment]
See: https://github.com/osgi/osgi.enroute.template/pull/6

**Pull request closed without merging**
